<a href="https://colab.research.google.com/github/somanath9094/aimlcourse/blob/main/Day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
name = 'Somanath Reddy'
name2 = 'Somanath Reddy Palle'
print(name)
print(name2)

Somanath Reddy
Somanath Reddy Palle


In [ ]:
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))

sum = num1 + num2
diff = num1 -  num2
product = num1 * num2
quotient = num1 / num2

print("Sum:", sum)
print("Difference:", diff)
print("Product:", product)
print("Quotient:", quotient)
print(num1 == num2)


Enter the first number: 21
Enter the second number: 21
Sum: 42.0
Difference: 0.0
Product: 441.0
Quotient: 1.0
True


DataTypes:
list
tuples
Dictionaries
sets


In [ ]:
#list
# it is a collection of mutuable and ordered items.
# mutuable items can be modified.

lst = []
print(lst[1:])
print(lst[1:3])
print(lst[1:7 : 2])

In [ ]:
fruits = ["apple", "banana", "cherry","date", "elderberry", "fig", "grape"]
print(fruits[1 : 5 : 3])
print(fruits[1 :  : 2])
print(fruits[2 : 5 : 2])
print(fruits[-2 : -6 : -1])

['banana', 'elderberry']
['banana', 'date', 'fig']
['cherry', 'elderberry']
['fig', 'elderberry', 'date', 'cherry']


In [ ]:
fruits = ["apple", "banana", "cherry","date", "elderberry", "fig", "grape"]

In [ ]:
#list comprehension
# create a lsit based on a logic or a rule or any linear syntax



lst1 = [x* x for x in range(6)]
print(lst1)

[0, 1, 4, 9, 16, 25]


In [ ]:
sq_rt = [x ** 0.5 for x in range(51)]
print(sq_rt)

[0.0, 1.0, 1.4142135623730951, 1.7320508075688772, 2.0, 2.23606797749979, 2.449489742783178, 2.6457513110645907, 2.8284271247461903, 3.0, 3.1622776601683795, 3.3166247903554, 3.4641016151377544, 3.605551275463989, 3.7416573867739413, 3.872983346207417, 4.0, 4.123105625617661, 4.242640687119285, 4.358898943540674, 4.47213595499958, 4.58257569495584, 4.69041575982343, 4.795831523312719, 4.898979485566356, 5.0, 5.0990195135927845, 5.196152422706632, 5.291502622129181, 5.385164807134504, 5.477225575051661, 5.5677643628300215, 5.656854249492381, 5.744562646538029, 5.830951894845301, 5.916079783099616, 6.0, 6.082762530298219, 6.164414002968976, 6.244997998398398, 6.324555320336759, 6.4031242374328485, 6.48074069840786, 6.557438524302, 6.6332495807108, 6.708203932499369, 6.782329983125268, 6.855654600401044, 6.928203230275509, 7.0, 7.0710678118654755]


In [ ]:
import math

In [ ]:
sqrt = [math.sqrt(x) for x in range(51)]
print(sqrt)

[0.0, 1.0, 1.4142135623730951, 1.7320508075688772, 2.0, 2.23606797749979, 2.449489742783178, 2.6457513110645907, 2.8284271247461903, 3.0, 3.1622776601683795, 3.3166247903554, 3.4641016151377544, 3.605551275463989, 3.7416573867739413, 3.872983346207417, 4.0, 4.123105625617661, 4.242640687119285, 4.358898943540674, 4.47213595499958, 4.58257569495584, 4.69041575982343, 4.795831523312719, 4.898979485566356, 5.0, 5.0990195135927845, 5.196152422706632, 5.291502622129181, 5.385164807134504, 5.477225575051661, 5.5677643628300215, 5.656854249492381, 5.744562646538029, 5.830951894845301, 5.916079783099616, 6.0, 6.082762530298219, 6.164414002968976, 6.244997998398398, 6.324555320336759, 6.4031242374328485, 6.48074069840786, 6.557438524302, 6.6332495807108, 6.708203932499369, 6.782329983125268, 6.855654600401044, 6.928203230275509, 7.0, 7.0710678118654755]


In [ ]:
#Nested Lists

In [ ]:
matrix  = [[1,2,3],[4,5,6],[7,8,9]]

print(matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [ ]:
matrix[2][2]

9

In [ ]:
multile = [[i * j for j in range(1,6)] for i in range(1,3)]
print(multile)

[[1, 2, 3, 4, 5], [2, 4, 6, 8, 10]]


In [ ]:
marks = [98, 95, 100, 100, 50, 56, 80]

# Corrected variable name
total_sum = sum(marks)  # Use built-in sum() function

print("Sum:", total_sum)
print("Max:", max(marks))
print("Min:", min(marks))
print("Average:", total_sum / len(marks))  # Corrected average calculation
print("Count:", len(marks))

Sum: 579
Max: 100
Min: 50
Average: 82.71428571428571
Count: 7


In [ ]:
# upacking with *
numbers = (1,2,3,4,5,6,7,8,9)

start, middle , *end = numbers

print(start, end)

1 [3, 4, 5, 6, 7, 8, 9]


In [ ]:
lst = [[1,2,3,4,5],[6,7,8,9,0],['hi','hello','tata']]
print(lst[1][1],lst[2][0])

7 hi


In [ ]:
lst2 = [[1,2,3,4,5],[6,7,8,9,0],('hi','hello','tata')]
print(lst2[1][1],lst2[2][0])

7 hi


In [3]:
numbers = [1,2,3,4,5,6,7,8,9]
numbers_grater_than_3 = list(filter( lambda x:x>3,numbers))
print(numbers_grater_than_3)

[4, 5, 6, 7, 8, 9]


In [6]:
with open('/content/sample_data/README.md','r') as file:
  content = file.read()
  print(content)

This directory includes a few sample datasets to get you started.

*   `california_housing_data*.csv` is California housing data from the 1990 US
    Census; more information is available at:
    https://docs.google.com/document/d/e/2PACX-1vRhYtsvc5eOR2FWNCwaBiKL6suIOrxJig8LcSBbmCbyYsayia_DvPOOBlXZ4CAlQ5nlDD8kTaIDRwrN/pub

*   `mnist_*.csv` is a small sample of the
    [MNIST database](https://en.wikipedia.org/wiki/MNIST_database), which is
    described at: http://yann.lecun.com/exdb/mnist/

*   `anscombe.json` contains a copy of
    [Anscombe's quartet](https://en.wikipedia.org/wiki/Anscombe%27s_quartet); it
    was originally described in

    Anscombe, F. J. (1973). 'Graphs in Statistical Analysis'. American
    Statistician. 27 (1): 17-21. JSTOR 2682899.

    and our copy was prepared by the
    [vega_datasets library](https://github.com/altair-viz/vega_datasets/blob/4f67bdaad10f45e3549984e17e1b3088c731503d/vega_datasets/_data/anscombe.json).



In [7]:
import os
cwd = os.getcwd()
print(cwd)

/content


In [8]:
new_dir = 'my_dir'
os.mkdir(new_dir)
print(f"newly created directory is {new_dir}")

newly created directory is my_dir


In [9]:
items = os.listdir('.')
print(items)

['.config', 'my_dir', 'sample_data']


In [11]:
dir_name = 'my_dir'
file_name = 'readme.md'
full_path = os.path.join(os.getcwd(),dir_name,file_name)
print(full_path)

('/content', ('my_dir', 'readme.md'))


In [2]:
import os
path = '/content/sample_data/README.md'

if os.path.isfile(path):
  print(f"THe path {path} is a file.")
elif os.path.isdir(path):
  print(f"THe path {path} is a Directory.")
else:
  print(f"The path {path} is neither file or directory")




THe path /content/sample_data/README.md is a file.


NUMPY


In [5]:
import numpy as np

In [3]:
lst1 = [1,2,3,4]

In [6]:
np.array(lst1)

array([1, 2, 3, 4])

In [8]:
matrix1 = [[1,2,3],[4,5,6]]
np.array(matrix1)

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.eye(4)  # identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.linspace(0,10,3, endpoint = False)  #linear space

array([0.        , 3.33333333, 6.66666667])

In [17]:
np.random.rand(2)

array([0.14669543, 0.50138068])

In [20]:
np.random.uniform(2,10,(4,4))

array([[9.19863073, 3.29414297, 7.21577242, 7.87661356],
       [4.37869619, 4.93504073, 2.06349295, 2.96796861],
       [3.36658606, 9.5325217 , 7.99997314, 5.27443985],
       [2.09627607, 7.15262909, 3.6258652 , 5.80974809]])

In [24]:
import pandas as pd
df =  pd.read_csv('/content/sample_data/california_housing_test.csv')
df.head(2)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0

In [27]:
df.describe()

longitude    latitude  housing_median_age   total_rooms  \
count  3000.000000  3000.00000         3000.000000   3000.000000   
mean   -119.589200    35.63539           28.845333   2599.578667   
std       1.994936     2.12967           12.555396   2155.593332   
min    -124.180000    32.56000            1.000000      6.000000   
25%    -121.810000    33.93000           18.000000   1401.000000   
50%    -118.485000    34.27000           29.000000   2106.000000   
75%    -118.020000    37.69000           37.000000   3129.000000   
max    -114.490000    41.92000           52.000000  30450.000000   

       total_bedrooms    population  households  median_income  \
count     3000.000000   3000.000000  3000.00000    3000.000000   
mean       529.950667   1402.798667   489.91200       3.807272   
std        415.654368   1030.543012   365.42271       1.854512   
min          2.000000      5.000000     2.00000       0.499900   
25%        291.000000    780.000000   273.00000       2.544000   
50%        437.000000   1155.000000   409.50000       3.487150   
75%        636.000000   1742.750000   597.25000       4.656475   
max       5419.000000  11935.000000  4930.00000      15.000100   

       median_house_value  
count          3000.00000  
mean         205846.27500  
std          113119.68747  
min           22500.00000  
25%          121200.00000  
50%          177650.00000  
75%          263975.00000  
max          500001.00000

In [30]:
df['population'].var()

1062018.9004316987